version: "3.9"
services:
  db:
    image: postgres:15
    container_name: fastfood-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastfood
    ports:
      - "5432:5432"
    volumes:
      - ./banco/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: sistema-backend
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DB_HOST: db
      DB_NAME: fastfood
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: flask run --host=0.0.0.0 --port=5000

  frontend:
    build: ./frontend
    container_name: front
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  postgres_data:
