FROM python:3.11-slim

# Definir diretório de trabalho
WORKDIR /app

# Copiar requirements e instalar dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo o backend
COPY . .

# Expor a porta do Flask
EXPOSE 5000

# Comando default (sobrescrito no docker-compose)
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
